server:
  port: 3000
  host: "localhost"

postgres:
  url: "localhost:5432"
  #  url: "db"
  user: "postgres"
  password: "1"
  name: "nevermore"
  driver: "postgres"

redis:
  url: "localhost:6379"
  #  url: redis
  password: ""

minio:
  endpoint: "localhost:9000"
  access_key: "miniouser"
  secret_key: "ohMyMinio"
  photoes: "photoes"
  pages: "pages"
  pdfs: "pdfs"

logger:
  dir: runtime/logs
  filename: ifc2-adapter-imilk.log
  level: INFO
  compress: true
  duplicate_to_stdout: true